// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu1MLc1AxfGPZP83NZJSsxkI_uyTuZWxM',
    appId: '1:1074900544359:web:18f5d8e8face27bb399dc2',
    messagingSenderId: '1074900544359',
    projectId: 'farmerseye-ykuq5i',
    authDomain: 'farmerseye-ykuq5i.firebaseapp.com',
    storageBucket: 'farmerseye-ykuq5i.firebasestorage.app',
    measurementId: 'G-X68EQH5R0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMLtst2CwtRgjY0j9PEZs4YQ4ybYpmnA',
    appId: '1:1074900544359:android:b0c62ba8d93b8511399dc2',
    messagingSenderId: '1074900544359',
    projectId: 'farmerseye-ykuq5i',
    storageBucket: 'farmerseye-ykuq5i.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59LAOJJZNgm_RyvkUVdzSuRfQZ1Usqao',
    appId: '1:1074900544359:ios:887592cd63f69a69399dc2',
    messagingSenderId: '1074900544359',
    projectId: 'farmerseye-ykuq5i',
    storageBucket: 'farmerseye-ykuq5i.firebasestorage.app',
    iosBundleId: 'com.example.gpsMain',
  );
}
